# Generated by Django 4.2.1 on 2023-06-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=40)),
                ('latitude', models.CharField(max_length=40)),
                ('ownerUsername', models.CharField(max_length=40)),
                ('careTakerDetails', models.CharField(max_length=200)),
            ],
        ),
    ]
