# Generated by Django 4.2.1 on 2023-06-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantID', models.IntegerField()),
                ('lastChecked', models.CharField(max_length=200)),
                ('typeDetails', models.CharField(max_length=200)),
                ('parentProject', models.IntegerField()),
            ],
        ),
    ]
