# Generated by Django 4.2.1 on 2023-06-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='plantStatus',
            field=models.CharField(default='orange', max_length=30),
            preserve_default=False,
        ),
    ]
