# Generated by Django 4.2.1 on 2023-06-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_plant_plantstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='careTakerDetails',
            new_name='careT',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='longitude',
            new_name='long',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='ownerUsername',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='project',
            name='zoomIn',
            field=models.IntegerField(default=12),
        ),
    ]
