# Generated by Django 4.2.1 on 2023-06-11 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_rename_caretakerdetails_project_caret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='healthDetails',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='lat',
            field=models.CharField(default='2023-04-23', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='long',
            field=models.CharField(default=20230220, max_length=40),
            preserve_default=False,
        ),
    ]
